from typing import Protocol

from contract_review.domain import (
    ApprovalAttachment,
    ApprovalTask,
    TaskLog,
)
from contract_review.results import CommentLog, ReviewResult
from contract_review.rules import RuleDefinition, RuleHit
from contract_review.versions import ReviewVersion


class TaskRepository(Protocol):
    def get_by_id(self, task_id: object) -> ApprovalTask | None: ...
    def get_by_external_key(self, external_key: str) -> ApprovalTask | None: ...
    def list_all(self) -> list[ApprovalTask]: ...
    def save(self, task: ApprovalTask) -> None: ...


class AttachmentRepository(Protocol):
    def get_by_id(self, attachment_id: object) -> ApprovalAttachment | None: ...
    def find_by_task_and_hash(self, task_id: object, file_hash: str) -> ApprovalAttachment | None: ...
    def list_by_task(self, task_id: object) -> list[ApprovalAttachment]: ...
    def save(self, attachment: ApprovalAttachment) -> None: ...
    def next_version(self, task_id: object) -> int: ...


class TaskLogRepository(Protocol):
    def append(self, log: TaskLog) -> None: ...
    def list_by_task(self, task_id: object) -> list[TaskLog]: ...
    def list_all(self, limit: int = 50, offset: int = 0) -> list[TaskLog]: ...
    def count_all(self) -> int: ...


class RuleRepository(Protocol):
    def get_by_id(self, rule_id: object) -> RuleDefinition | None: ...
    def list_all(self) -> list[RuleDefinition]: ...
    def list_published(self) -> list[RuleDefinition]: ...
    def save(self, rule: RuleDefinition) -> None: ...


class ReviewResultRepository(Protocol):
    def get_by_id(self, result_id: object) -> ReviewResult | None: ...
    def get_latest_by_task(self, task_id: object) -> ReviewResult | None: ...
    def save(self, result: ReviewResult) -> None: ...
    def list_by_task(self, task_id: object) -> list[ReviewResult]: ...


class CommentLogRepository(Protocol):
    def append(self, log: CommentLog) -> None: ...
    def list_by_task(self, task_id: object) -> list[CommentLog]: ...


class VersionRepository(Protocol):
    def save(self, version: ReviewVersion) -> None: ...
    def list_by_task(self, task_id: object) -> list[ReviewVersion]: ...
    def get_by_id(self, version_id: object) -> ReviewVersion | None: ...
